.SUFFIXES:

sintactico: main.o y.tab.o lex.yy.o
	gcc -o sintactico main.o y.tab.o lex.yy.o

y.tab.o: y.tab.c
	gcc -c y.tab.c

lex.yy.o: lex.yy.c
	gcc -c lex.yy.c

main.o: main.c
	gcc -c main.c

y.tab.c: sintactico.y lex.yy.o
	bison -d --report=state -o y.tab.c sintactico.y

lex.yy.c: lexico.l
	flex lexico.l

clean:
	rm -f sintactico main.o y.tab.o y.tab.h y.tab.c y.output lex.yy.c

all:
	make clean
	make sintactico
